### ISSUE TITLE
Timeout is not evaluated correcty

### ISSUE THREAD

**Issue by kalymero** [podium/redis_mutex#7]
I have a use case where it would be helpful to have a timeout < ttl to make sure that if the lock is already acquired, after a given timeout, other instances will give up on the task.

Just find out that the timeout is not properly evaluated. 

In particular it seems that the `finish` value here https://github.com/podium/redis_mutex/blob/master/lib/redis_mutex/lock.ex#L87 should be compared against the actual timestamp (`Timex.now()`) instead that the `start` value

**Comment by cjpwrs** [comment]
@kalymero That's a good catch! Seems like we wouldn't even need to pass in a `start` time ever. We should always just be checking against `Timex.now()`. What do you think?

**Comment by kalymero** [comment]
agree
